Added Interface Settings
iamEzmuth/DeAuthImposter pull request #1
Opened 2022-05-26 19:59 UTC by Bhavya0304

### Issue!
--> whenever someone try to use this script there were chances of error because Network Interface card name was hard coded so if the name of NIC is different on those computer script won't work 

### Fix
--> added a functionality to write network interface card name as command line argument!

2022-05-26 20:19 UTC, iamEzmuth commented on deauthimposter.py
>  user_arg = sys.argv[1]
Add conditions to check whether the args supplied or not!

2022-05-26 20:19 UTC, iamEzmuth commented on deauthimposter.py
> +user_interface = sys.argv[2]
Add conditions to check whether the args supplied or not!

2022-05-26 20:41 UTC, iamEzmuth requested changes
If you are really willing to contribute that's OK , first of all  i am so glad actually i created this script for my own sake but if you want to make it better that's great!

### Points to Focus: 

- If you are adding a new arg in main python file than update read-me file accordingly.
- I have reviewed the code and commented the issues. looks like you are new to contribution field no worries at all.
- Please verify and run the code on local machine before PR.
- if if if if and only if you are willing to help you can add a small section of help argument on main python file as you would have noticed in almost all Linux shell scripts (e.x --help) that provides basic arguments info. (If you are not willing to complete this final point its completely up-to you i will still approve and merge this PR )  

------BEST OF LUCK------

2022-05-26 20:41 UTC, iamEzmuth commented on Requires/premethods.sh
> +if ["$1"]; then
i am not sure this will work please ensure before committing

2022-05-26 20:41 UTC, iamEzmuth commented on Requires/premethodsfix.sh
> +if ["$1"]; then
i am not sure this will work please ensure before committing

2022-05-26 20:41 UTC, iamEzmuth commented on Requires/premethods.sh
> +
every if/else statements in shell scripting ends with fi

2022-05-26 20:41 UTC, iamEzmuth commented on Requires/premethodsfix.sh
> +
every if/else statements in shell scripting ends with fi

2022-05-27 15:52 UTC, Bhavya0304 commented on README.md
> +    sudo pip3 install -r Requirements.txt
added requirements file

2022-06-04 22:21 UTC, iamEzmuth approved these changes
Great Work!!! 
There still some fixes to solve but for now I am merging your request and will add those fixes to issues tab you can work on them if you want.

2022-06-04 22:22 UTC, merged